CREATE TABLE IF NOT EXISTS curs_data (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currency_name VARCHAR(3) NOT NULL,
    currency_code NUMERIC(3) NOT NULL,
    curs NUMERIC(5, 2) NOT NULL,
    curs_date DATE
)