spring.datasource.url=jdbc:postgresql://localhost:5432/currency_ds
spring.datasource.username=postgres
spring.datasource.password=123Nikita2609

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

spring.liquibase.change-log=classpath:db/changelog/changelog.xml

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.password=admin
spring.activemq.user=admin

logging.pattern.console=%msg%n
logging.level.ru.ds.education.currency=debug
logging.level.org.springframework=info